[package]
name = "rscript_transformers"
version.workspace = true
edition.workspace = true

[dependencies]
rscript_core = { workspace = true }
rscript_ast = { workspace = true }
bumpalo = { workspace = true }
regex = { workspace = true }
